[workspace]
resolver = "2"
members = ["explora", "common", "server", "server-cli"]
default-members=["explora"]


[workspace.dependencies]
tracing = "0.1.40"
vek = "0.16.1"
quinn = { version =  "0.11.0", features = ["ring"]}
